version: "3"

services:

  app:
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=database
    ports:
      - "8080:8080"
    volumes:
      - ./app:/opt/app
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: EXAMPLE
    ports:
      - "5432:5432"